spring:
  config:
    activate:
      on-profile: default
  jpa:
#    show-sql: true
    properties:
      hibernate:
#        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        query:
          in_clause_parameter_padding=true:defer-datasource-initialization: true
    defer-datasource-initialization: true

  datasource:
    url: jdbc:mysql://sports-echo-mysql-instance.c8cvx8gfy4m3.ap-northeast-2.rds.amazonaws.com/echo_db
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    redis:
      host: 13.125.46.61
      port: 6379
    mongodb:
      uri: mongodb://localhost:27017/echo_db

jwt:
  secret_key: ${JWT_SECRET_KEY}

api-keys:
  football: ${FOOTBALL_API_KEY}
  basketball: ${BASKETBALL_API_KEY}
  baseball: ${BASEBALL_API_KEY}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: sports-echo

oauth:
  api:
    secret:
      naver: ${NAVER_API_SECRET}
      google: ${GOOGLE_API_SECRET}
    key:
      kakao: ${KAKAO_API_KEY}
      naver: ${NAVER_API_KEY}
      google: ${GOOGLE_API_KEY}

admin:
  key:
    secret: ${ADMIN_SECRET_KEY}